language: php
dist: precise

notifications:
  email: false

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - NO_INTERACTION=1
    - REPORT_EXIT_STATUS=1

before_script:
  - phpize
  - ./configure 
  - make

script: make test

after_failure: "cat tests/*.diff"
